name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f yaaarslv/Lab1/pom.xml -f yaaarslv/Lab2/pom.xml -f yaaarslv/Lab3/pom.xml -f yaaarslv/Lab4/pom.xml -f yaaarslv/Lab5/pom.xml --batch-mode --update-snapshots package
